### ISSUE TITLE
Newsletter form wrong on Safari iOS

### ISSUE THREAD

**Issue by Mamboleoo** [maeligg/creative-frontend-belgium#36]
See screenshot, there is an extra unwanted border-radius. 
![34D8FEE1-FC1B-40ED-9B61-7C7468A6B67E](https://user-images.githubusercontent.com/6048794/69912244-b79c2d80-1426-11ea-83b4-8941ff1e10ba.png)

**Comment by maeligg** [comment]
![EK-FhF0U0AAkCPK](https://user-images.githubusercontent.com/9273118/70255020-59ed4580-1786-11ea-95dc-79460ee2fab3.jpg)
